# Generated by Django 5.2.3 on 2025-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=100)),
                ('email', models.EmailField(max_length=254, verbose_name=100)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
